- name: Load user description data
  include_vars:
    file: "{{ users_dir }}/{{ remote_user }}.yml"
    name: user_data
- name: "Create user home for {{ user_data.name }}"
  block:
    - name: Create user
      user:
        name: "{{ user_data.name }}"
        comment: "{{ user_data.comment | default('User populated by Ansible playbook users-setup') }}"
        create_home: True
        password: "{{ user_data.password | default('!') }}"
        shell: "{{ user_data.shell | default('/bin/bash') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        system: "{{ user_data.system | default(False) }}"
        state: present
    - name: Create desktop user directories
      become: true
      become_user: "{{ user_data.name }}"
      file:
        path: "{{ home_dir }}/{{ item.value }}"
        state: directory
      loop: "{{ xdg|dict2items }}"
    - name: Create extra user directories
      become: true
      become_user: "{{ user_data.name }}"
      file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
      loop: "{{ extra }}"
  when: user_data['state'] == "create" or user_data['state'] == "all"
- name: Setup XDG environment
  block:
    - name: Create XDG configuration directory
      file:
        path: "{{ home_dir }}/.config"
        state: directory
    - name: Deploy XDG configuration file
      template:
        src: user-dirs.dirs.j2
        dest: "{{ home_dir }}/.config/user-dirs.dirs"
    - name: Create repository directory in XDG local directory
      file:
        path: "{{ home_dir }}/.local/configs"
        state: directory
  become: true
  become_user: "{{ user_data.name }}"
  when: user_data['state'] == "config" or user_data['state'] == "all"
