###
# Allows setting up the StumpWM window manager.
#
# The playbook ensure that all dependencies are installed before
# compiling the application.
#
- hosts: all
  gather_facts: False
  tasks:
    - name: Load user description data
      include_vars:
        file: "{{ users_dir }}/builder.yml"
        name: user_data
    - name: Ensure QuickLisp is installed
      include_role:
        name: quicklisp
      vars:
        working_directory: "{{ git_3rdparty }}/{{ applications['common_lisp']['ql_repo_dir'] }}"
      when: applications['common_lisp'] is defined
    - name: Deploy StumpWM
      include_role:
        name: stumpwm
      vars:
        repository: "{{ applications['stumpwm']['repo'] }}"
        repository_contrib: "{{ applications['stumpwm']['repo_contrib'] }}"
        working_dir: "{{ git_3rdparty }}/{{ applications['stumpwm']['dir'] }}"
      when: applications['stumpwm'] is defined
