###
# Playbook to setup the builder user.
#
# This user is meant to build applications to be used on the target
# host.
# 
- hosts: all
  gather_facts: False
  tasks:
    - name: Load user description data
      include_vars:
        file: "{{ users_dir }}/builder.yml"
        name: user_data
    - name: Create the user
      include_role:
        name: manage-user
    - name: Update configuration repositories and deploy XDG compliant configuration elements
      include_role:
        name: common
        tasks_from: manage-cfg.yml
      loop: "{{ user_data.configurations|dict2items }}"
      loop_control:
        loop_var: user_conf
    - name: Deploy other configuration elements
      include_role:
        name: user-configuration
    - name: Ensure QuickLisp is installed
      include_role:
        name: quicklisp
      vars:
        working_directory: "{{ git_3rdparty }}/{{ applications.common_lisp.ql_repo_dir }}"
      when: applications['common_lisp'] is defined
