---
- hosts: all
  gather_facts: False
  tasks:
    - name: Deploy StumpWM
      include_role:
        name: stumpwm
      vars:
        repository: "{{ applications.stumpwm.repo }}"
        repository_contrib: "{{ applications.stumpwm.repo_contrib }}"
        working_dir: "{{ git_3rdparty }}/{{ applications.stumpwm.dir}}"
