# The host user must be root.
---
- hosts: all
  gather_facts: False
  tasks:
    - name: "Create user environement"
      include_role:
        name: config-xdg
      loop: "{{ users }}"
      loop_control:
        loop_var: remote_user
    - name: "Install Python dependencies"
      include_role:
        name: python
      loop: "{{ users }}"
      loop_control:
        loop_var: remote_user
