# The host user must be root.
---
- hosts: all
  gather_facts: False
  tasks:
    - name: "Create user environement"
      include_role:
        name: config-xdg
    - name: "Install Python dependencies"
      include_role:
        name: python
