- name: Install dependencies
  command: sbcl --disable-debugger --eval "(progn (ql:quickload \"clx\") (ql:quickload \"cl-ppcre\") (ql:quickload \"alexandria\") (exit))"
  become: True
  become_user: builder
- name: Set permission on StumpWM working directory
  file:
    path: "{{ git_3rdparty }}/{{ applications.stumpwm.dir }}"
    state: directory
    recurse: True
    owner: builder
    group: builder
- name: Build configure script
  command: ./autogen.sh
  args:
    chdir: "{{ git_3rdparty }}/{{ applications.stumpwm.dir }}"
  become: True
  become_user: builder
- name: Configure StumpWM
  command: ./configure
  args:
    chdir: "{{ git_3rdparty }}/{{ applications.stumpwm.dir }}"
  become: True
  become_user: builder
- name: Compile StumpWM
  command: make
  args:
    chdir: "{{ git_3rdparty }}/{{ applications.stumpwm.dir }}"
  become: True
  become_user: builder
- name: Install StumpWM
  command: make install
  args:
    chdir: "{{ git_3rdparty }}/{{ applications.stumpwm.dir }}"
