# - name: Ensure .emacs.d/ directory is empty
#   file:
#     path: ~/.emacs.d
#     state: absent
# - name: Create target directory
#   file:
#     path: ~/.emacs.d
#     state: directory
- name: Deploy init.el
  copy:
    src: "{{ root_config_repo }}/{{ emacs.dir }}/{{ item.src }}"
    dest: ~/.emacs.d
  with_items:
    # - src: init.emacs.org
    - src: init.el
