- name: Ensure .tmux directory is empty
  file:
    path: "{{ user_home_dir }}/.tmux"
    state: absent
- name: Deploy configuration files
  copy:
    remote_src: "{{ root_config_repo }}/{{ tmux.dir }}/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
  with_item:
    - tmux
    - tmux.conf
