- name: Load user description data
  include_vars:
    file: "{{ users_dir }}/builder.yml"
    name: user_data
- name: Create the user
  include_role:
    name: manage-user
    tasks_from: user-init.yml
- name: Configure git environment for the builder user
  include_role:
    name: manage-user
    tasks_from: git.yml
- name: Update configuration repositories and deploy XDG compliant configuration elements
  include_role:
    name: manage-user
    tasks_from: xdg-conf.yml
  loop: "{{ user_data.configurations|dict2items }}"
  loop_control:
    loop_var: user_conf
- name: Deploy other configuration elements
  include_role:
    name: manage-user
    tasks_from: non-xdg-conf.yml
