- name: local monitoring CLI
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - ftop
    - iftop
    - net-tools
    - sysstat
    - glances

- name: Mobile SHell
  dnf:
    name: "mosh"
    state: latest

- name: direnv
  dnf:
    name: "direnv"
    state: latest

- name: zsh
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - zsh
    - powerline
    - powerline-docs
    - powerline-fonts

- name: Python3 execution environment
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - python3
    - python3-pip

- name: Git repositories management
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - git-core
    - git-core-doc
    - libgit2
    - perl-Git
    - python3-pygit2

- name: TMux - Terminal Multiplexer
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - tmux
    - tmux-powerline

- name: Neofetch
  dnf:
    name: "neofetch"
    state: latest

- name: Terminal File Manager
  dnf:
    name: "ranger"
    state: latest

- name: Deploy 3rd party applications common to any hosts
  include_tasks: common-3rdparty.yml
