- name: Debug
  debug:
    var: user_conf
- name: Debug 2
  debug:
    var: config_data
- name: "{{ user_conf.key }} configuration processing"
  block:
    - name: Checkout lastest version of configuration repository
      git:
        repo: "{{ config_data.repo }}"
        dest: "{{ root_config_repo }}/{{ config_data.dir }}"
        version: 'HEAD'
      when: config_data['checkout'] == True
    - name: Deploy XDG compliant configuration
      block:
        - name: Delete old configuration directory
          file:
            path: "{{ xdg_config_home }}/{{ config_data.xdgdir }}"
            state: absent
          when: config_data['delete_xdgdir_first'] == True)
        - name: Create new configuration directory
          file:
            path: "{{ xdg_config_home }}/{{ config_data.xdgdir }}"
            state: directory
          with_filetree: "{{ root_config_repo }}/{{ config_data.dir }}"
          when: item.state == 'directory'
        - name: Deploy new configuration resources
          copy:
            src: "{{ root_config_repo }}/{{ config_data.dir }}/{{ item }}"
            dest: "{{ xdg_config_home }}/{{ config_data.xdgdir }}"
          loop: "{{ config_data.files }}"
      when: config_data['xdg_compliant'] == True)
  when: config_data['config'] == True)
