- name: "{{ user_conf.key }} configuration processing"
  block:
    - name: Checkout lastest version of configuration repository
      git:
        repo: "{{ user_conf.repo }}"
        dest: "{{ root_config_repo }}/{{ user_conf.dir }}"
        version: 'HEAD'
      when: (user_conf['checkout'] is defined and user_conf['checkout'] == True) or
            (actions['checkout'] == True and user_conf['checkout'] is undefined)
    - name: Deploy XDG compliant configuration
      block:
        - name: Delete old configuration directory
          file:
            path: "{{ xdg_config_home }}/{{ user_conf.xdgdir }}"
            state: absent
          when: (user_conf['delete_xdgdir_first'] is defined and user_conf['delete_xdgdir_first'] == True) or
                (actions['delete_xdgdir_first'] == True and user_conf['delete_xdgdir_first'] is undefined)
        - name: Create new configuration directory
          file:
            path: "{{ xdg_config_home }}/{{ user_conf.xdgdir }}"
            state: directory
        - name: Deploy new configuration resources
          copy:
            src: "{{ root_config_repo }}/{{ user_conf.dir }}/{{ item }}"
            dest: "{{ xdg_config_home }}/{{ user_conf.xdgdir }}"
          loop: "{{ applic.files }}"
      when: (user_conf['xdg_compliant'] is defined and user_conf['xdg_compliant'] == True) or
            (actions['xdg_compliant'] == True and user_conf['xdg_compliant'] is undefined)
  when: (applic['config'] is defined and applic['config'] == True) or
        (actions['config'] == True and applic['config'] is undefined)
