### ----------------------------------------
# Remove remains of previous configuration
- name: Delete configuration directory zsh
  file:
    path: "{{ user.xdghomeconfig }}/{{ applic.xdgdir }}"
    state: absent
  when:
    - (applic['delete_xdgdir_first'] is defined and applic['delete_xdgdir_first'] == True) or
      (actions['delete_xdgdir_first'] == True and applic['delete_xdgdir_first'] is undefined)
### ----------------------------------------
# .zshrc must remain in the $HOME directory of the user
- name: Deploy .zshrc
  copy:
    src: "{{ conf.conf_repo }}/{{ applic.dir }}/.zshrc"
    dest: "{{ user.home }}"
### ----------------------------------------
# The rest of the configuration is expected to be stored following the
# XDG specification.  Doing it that way, ensure that the root of the
# home directory stay as clean as possible.
- name: Create new XDG configuration directory for zsh
  file:
    path: "{{ user.xdghomeconfig }}/{{ applic.xdgdir }}"
    state: directory
- name: Deploy new configuration resources for zsh
  copy:
    src: "{{ conf.conf_repo }}/{{ applic.dir }}/{{ item }}"
    dest: "{{ user.xdghomeconfig }}/{{ applic.xdgdir }}"
  loop: "{{ applic.files }}"
### ----------------------------------------
