- name: Include common variables
  include_vars:
    file: ../../common/vars/main.yml
- name: "Update non XDG compliant configuration"
  block:
    ### ----------------------------------------
    # .zshrc must remain in the $HOME directory of the user.  The rest of
    # the zsh configuration is stored in the $XDG_CONFIG_HOME directory.
    - name: Deploy .zshrc
      copy:
        src: "{{ root_config_repo }}/{{ applications.zsh.dir }}/zshrc"
        dest: "{{ user_home }}/.zshrc"
      when: (actions['config'] == True and user_data['configurations']['zsh']['config'] is undefined) or
            (user_data['configurations']['zsh']['config'] is defined and user_data['configurations']['zsh']['config'] == True)
    # ------------------------------------------
    - name: Deploy TMux configuration
      include_role:
        name: tmux
      when:
        - (actions['config'] == True and user_data['configurations']['tmux']['config'] is undefined) or
          (user_data['configurations']['tmux']['config'] is defined and user_data['configurations']['tmux']['config'] == True)
    - name: Deploy Emacs configuration
      include_role:
        name: emacs
      when:
        - (actions['config'] == True and user_data['configurations']['emacs']['config'] is undefined) or
          (user_data['configurations']['emacs']['config'] is defined and user_data['configurations']['emacs']['config'] == True)
  become: True
  become_user: "{{ user_data.name }}"
